//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleSpec
{
    using System;
    using System.Collections.Generic;
    
    public partial class adCharts
    {
        public int ID { get; set; }
        public Nullable<int> cYear { get; set; }
        public string cMonth { get; set; }
        public Nullable<int> VCA { get; set; }
        public Nullable<int> VCB { get; set; }
        public Nullable<int> VCC { get; set; }
        public Nullable<int> VCD { get; set; }
    }
}
